### ISSUE TITLE
[DESIGN] First draft room generation logic (LDD)

### ISSUE THREAD

**Issue by waiteng-kwan** [Deep-Dovers/deep-divers#4]
To do:
- Define what room types there are
- Define how navigating from room to room should work in a multiplayer setting
- Define how room to room connections work if there is generated dungeons

Document link: https://docs.google.com/document/d/1lhETYKVq72JaRH-bZDrn4P7n_3UvaVGV/edit?usp=sharing&ouid=113217168394624476354&rtpof=true&sd=true

Update To Do:
- Create visual examples of how the generation is expected to work
- Create rules how generation starts
- Create dimension of maximum size of the empty cells in the "map"

**Comment by Hamimizan** [comment]
Still WIP

**Comment by Hamimizan** [comment]
Finished with first iteration and logic

**Comment by Hamimizan** [comment]
Left to discuss with Ramly on 14/05 2030

**Comment by Hamimizan** [comment]
Discussed with Ramly and anything left to add will open new task for that specifically closing with this comment.
