### ISSUE TITLE
[DESIGN] Relic/Powerup GDD

### ISSUE THREAD

**Issue by waiteng-kwan** [Deep-Dovers/deep-divers#5]
Initial To Do:
- Outline high level Relic system

Document Link: https://docs.google.com/document/d/19FPeAx0NTitVsxAbg79FQmvzDeT6wDa0VmTIZsrgZPY/edit?usp=sharing

Update To Do:
- Curate a initial list of relics based on the high level design
- UI Wireframe of the gameplay and management aspect of relics

**Comment by Hamimizan** [comment]
Todo still:
- Management screen

**Comment by Hamimizan** [comment]
Closing as finished with task. If anything needed will open new issue specific to that.
